---
Name: project-routes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'process-do-imports': 'CatchDesign\SSBGExportImport\ProcessDOImports'
    'process-do-exports': 'CatchDesign\SSBGExportImport\ProcessDOExports'
    'process-do-purges': 'CatchDesign\SSBGExportImport\ProcessDOPurges'
    'ExportFileExporter//$Action/$ID': 'CatchDesign\SSBGExportImport\ExportFileExporter'
