---
Name: project-routes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'process-do-imports': 'ProcessDOImports'
    'process-do-exports': 'ProcessDOExports'
    'process-do-purges': 'ProcessDOPurges'
    'ExportFileExporter//$Action/$ID': 'ExportFileExporter'
